package com.realtimeaudio

import com.facebook.react.bridge.Arguments
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReadableMap
import com.facebook.react.bridge.WritableMap
import com.facebook.react.modules.core.DeviceEventManagerModule

/**
 * IMPORTANT:
 * Do NOT declare NativeRealtimeAudioAnalyzerSpec yourself.
 * This class is generated by RN Codegen based on your TS Spec.
 *
 * After codegen runs, it will be available in this package:
 *   com.realtimeaudio.NativeRealtimeAudioAnalyzerSpec
 */
class RealtimeAudioAnalyzerModule(
  reactContext: ReactApplicationContext
) : NativeRealtimeAudioAnalyzerSpec(reactContext) {

  companion object {
    const val NAME = "RealtimeAudioAnalyzer"
  }

  private var listenerCount = 0
  private val engine = AudioEngine { data -> sendEvent(data) }

  override fun getName(): String = NAME

  override fun startAnalysis(config: ReadableMap, promise: Promise) {
    try {
      val bufferSize = when {
        config.hasKey("bufferSize") -> config.getInt("bufferSize")
        config.hasKey("bufferSizeFrames") -> config.getInt("bufferSizeFrames")
        else -> 1024
      }
      val sampleRate = if (config.hasKey("sampleRate")) config.getInt("sampleRate") else 48000
      val fftSize = when {
        config.hasKey("fftSize") -> config.getInt("fftSize")
        else -> 1024
      }
      val callbackRateHz = if (config.hasKey("callbackRateHz")) config.getInt("callbackRateHz") else 30
      val enableFft = if (config.hasKey("enableFft")) config.getBoolean("enableFft") else true
      val emitTimeData = if (config.hasKey("enableTimeData")) config.getBoolean("enableTimeData") else true
      val debugPitch = if (config.hasKey("debugPitch")) config.getBoolean("debugPitch") else false
      val calibrationA4Hz: Double? = when {
        config.hasKey("calibrationA4Hz") -> config.getDouble("calibrationA4Hz")
        config.hasKey("a4Hz") -> config.getDouble("a4Hz")
        else -> null
      }

      engine.start(
        AnalyzerConfig(
          bufferSizeFrames = bufferSize,
          sampleRateHz = sampleRate,
          fftSize = fftSize,
          callbackRateHz = callbackRateHz,
          enableFft = enableFft,
          enableTimeData = emitTimeData,
          calibrationA4Hz = calibrationA4Hz,
          debugPitch = debugPitch
        )
      )
      promise.resolve(null)
    } catch (e: SecurityException) {
      promise.reject("E_PERMISSION_DENIED", "Microphone permission denied: ${e.message}", e)
    } catch (e: Exception) {
      promise.reject("E_START_FAILED", e.message ?: "Unknown error occurred", e)
    }
  }

  override fun stopAnalysis(promise: Promise) {
    engine.stop()
    promise.resolve(null)
  }

  override fun isAnalyzing(promise: Promise) {
    promise.resolve(engine.isRecording())
  }

  override fun getAnalysisConfig(promise: Promise) {
    val config = Arguments.createMap().apply {
      putInt("bufferSizeFrames", 1024)
      putInt("fftSize", 1024)
      putInt("sampleRate", 44100)
      putInt("callbackRateHz", 30)
      putBoolean("enableFft", true)
      putString("windowFunction", "hanning")
      putDouble("smoothing", 0.8)
    }
    promise.resolve(config)
  }

  // Legacy aliases (if in your TS Spec)
  override fun start(options: ReadableMap, promise: Promise) =
    startAnalysis(options, promise)

  override fun stop(promise: Promise) =
    stopAnalysis(promise)

  override fun isRunning(promise: Promise) =
    isAnalyzing(promise)

  override fun setSmoothing(enabled: Boolean, factor: Double, promise: Promise) {
    engine.setSmoothing(enabled, factor.toFloat())
    promise.resolve(null)
  }

  override fun setFftConfig(fftSize: Double, downsampleBins: Double, promise: Promise) {
    engine.setFftConfig(fftSize.toInt(), downsampleBins.toInt())
    promise.resolve(null)
  }

  override fun setTimeDataConfig(enabled: Boolean, promise: Promise) {
    engine.setTimeDataConfig(enabled)
    promise.resolve(null)
  }

  override fun addListener(eventName: String) {
    listenerCount++
  }

  override fun removeListeners(count: Double) {
    listenerCount -= count.toInt()
    if (listenerCount < 0) listenerCount = 0
  }

  private fun sendEvent(data: AudioEngine.AudioData) {
    if (listenerCount <= 0 || !reactApplicationContext.hasActiveReactInstance()) return

    fun params(): WritableMap =
      Arguments.createMap().apply {
        putDouble("timestamp", data.timestamp)
        putDouble("rmsDb", data.rmsDb)
        putDouble("peakDb", data.peakDb)
        putDouble("volume", data.rms) // Keep for backward compatibility if needed
        putDouble("peak", data.peak)   // Keep for backward compatibility if needed
        putInt("sampleRate", data.sampleRate)
        putInt("fftSize", data.bufferSize)

        val freq = Arguments.createArray()
        data.fft?.forEach { freq.pushDouble(it.toDouble()) }
        putArray("frequencyData", freq)
        
        val timeArray = Arguments.createArray()
        data.timeData?.forEach { timeArray.pushDouble(it.toDouble()) }
        putArray("timeData", timeArray)
      }

    reactApplicationContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
      .emit("RealtimeAudioAnalyzer:onData", params())

    data.pitch?.let { emitPitchUpdate(it) }
  }

  private fun emitPitchUpdate(result: PitchResult) {
    if (listenerCount <= 0 || !reactApplicationContext.hasActiveReactInstance()) return

    val payload: WritableMap =
      Arguments.createMap().apply {
        if (result.detectedFrequency != null) putDouble("detectedFrequency", result.detectedFrequency) else putNull("detectedFrequency")
        if (result.noteName != null) putString("noteName", result.noteName) else putNull("noteName")
        if (result.octave != null) putInt("octave", result.octave) else putNull("octave")
        if (result.centsOffset != null) putDouble("centsOffset", result.centsOffset) else putNull("centsOffset")
        putDouble("confidence", result.confidence)
        if (result.inputLevel != null) putDouble("inputLevel", result.inputLevel) else putNull("inputLevel")
        putBoolean("isStable", result.isStable)
        putString("tuningState", result.tuningState.serialized)

        // Optional debug payload (off by default).
        result.debug?.let { d ->
          val dbg = Arguments.createMap().apply {
            if (d.rawFrequencyHz != null) putDouble("rawFrequencyHz", d.rawFrequencyHz) else putNull("rawFrequencyHz")
            putDouble("compositeConfidence", d.compositeConfidence)
            putDouble("cmndMin", d.cmndMin)
            putDouble("harmonicConsistency", d.harmonicConsistency)
            putDouble("fftSupport", d.fftSupport)
            putInt("chosenDivisor", d.chosenDivisor)
            if (d.inputLevelDbfs != null) putDouble("inputLevelDbfs", d.inputLevelDbfs) else putNull("inputLevelDbfs")
            putDouble("noiseFloorDbfs", d.noiseFloorDbfs)
            putDouble("smoothingAlpha", d.smoothingAlpha)
            putDouble("requiredStableWindowSec", d.requiredStableWindowSec)
            putInt("lastTau", d.lastTau)
          }
          putMap("debug", dbg)
        }
      }

    reactApplicationContext
      .getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter::class.java)
      .emit("RealtimeAudioAnalyzer:onPitch", payload)
  }
}